version: 2
jobs: 
  build:
    docker: 
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "79:b4:0c:34:0e:30:68:8c:8c:44:5e:f1:ce:a7:62:be"
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build